
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'iSecure' do
    pod 'Alamofire', '3.1.3'
    pod 'ObjectMapper', '1.1.4'
    pod 'Kingfisher', '~> 1.8'
end
